# Generated by Django 6.1.1 on 2026-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
