# Generated by Django 6.1.1 on 2026-10-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_profile_is_online_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
